export async function onRequest(context) {
  const url = new URL(context.request.url);
  const platform = context.request.headers.get("expo-platform") || "android";
  const runtimeVersion = context.request.headers.get("expo-runtime-version") || "1.0.0";

  try {
    // 1. Fetch the metadata.json generated by `npx expo export`
    const metadataUrl = new URL("/metadata.json", url.origin);
    const metadataRes = await context.env.ASSETS.fetch(metadataUrl);
    
    if (!metadataRes.ok) {
      return new Response("No update metadata found", { status: 404 });
    }

    const metadata = await metadataRes.json();
    const fileMetadata = metadata.fileMetadata[platform];

    if (!fileMetadata) {
      return new Response(`Platform ${platform} not found in build`, { status: 404 });
    }

    // 2. Build the Expo Updates Protocol v1 Response
    const manifest = {
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      runtimeVersion: runtimeVersion,
      launchAsset: {
        key: fileMetadata.bundle,
        contentType: "application/javascript",
        url: `${url.origin}/${fileMetadata.bundle}`,
      },
      assets: (fileMetadata.assets || []).map((asset) => ({
        key: asset.path,
        contentType: asset.ext ? `image/${asset.ext}` : "application/octet-stream",
        url: `${url.origin}/${asset.path}`,
      })),
      metadata: {},
      extra: {
        expoClient: {
          name: "Arrow Puzzle",
          slug: "arrow-puzzle",
        },
      },
    };

    // 3. Return the JSON with the required Expo protocol headers
    return new Response(JSON.stringify(manifest), {
      headers: {
        "Content-Type": "application/json",
        "expo-protocol-version": "1",
        "expo-sfv-version": "0",
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
    });
  } catch (err) {
    return new Response(`Server error: ${err.message}`, { status: 500 });
  }
}